# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='review',
            name='width_field',
        ),
    ]
