# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-23 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
