# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=person.models.scramble_uploaded_filename, width_field='width_field'),
        ),
    ]
