# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import topic.models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='pic',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=topic.models.scramble_uploaded_filename, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='topic',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
