# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='caption',
            field=models.CharField(default='', max_length=200),
        ),
    ]
